---
title: "FICB Communities"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, 
                      warning = F,
                      message = F,
                      fig.width = 10,
                      dpi = 300)


library(tidyverse)
library(tidycensus)
library(googlesheets)
library(readxl)
library(janitor)
library(hrbrmisc)
library(hrbrthemes)
library(scales)
library(ggthemes)


theme_set(theme_minimal(base_size = 18))

source("get_data.R")
source("get_shapefiles.R")

tfff.dark.green <- "#265142"
tfff.light.green <- "#B5CC8E"
tfff.orange <- "#e65100"
tfff.yellow <- "#FBC02D"
tfff.blue <- "#283593"
tfff.red <- "#B71C1C"
tfff.brown <- "#51261C"
tfff.dark.gray <- "#545454"
tfff.medium.gray <- "#a8a8a8"
tfff.light.gray <- "#eeeeee"



dk_or_ca_map <- function() {
     ggplot(or_ca_map) +
          geom_sf(fill = "white") +
          coord_sf(datum = NA) +
          theme(axis.title = element_blank())
}

```


# Population Size

## Histogram

```{r}

ggplot(pop_size, aes(estimate)) +
     geom_histogram(bins = 10) +
     scale_x_continuous(labels = comma_format(),
                        limits = c(0, 45000)) +
     scale_y_continuous(limits = c(0, 15)) +
     labs(x = "Population",
          y = "Number of communities")
```

## Map

```{r fig.height=10}
dk_or_ca_map() +
     geom_point(data = pop_size, aes(longitude, latitude,
                                     size = estimate),
                alpha = 0.7,
                color = tfff.dark.green) +
     labs(size = "Population") +
     scale_size_continuous(labels = comma_format())

```


# Core County

## Pie chart


```{r}

core_county %>% 
     group_by(core) %>% 
     count() %>% 
     ungroup() %>% 
     ggplot(aes(x = "", y = core, fill = core)) +
     geom_bar(width = 1, stat = "identity") +
     coord_polar("y") +
     geom_text(aes(label = str_glue("{core}\n{n}")), position = position_stack(vjust = 0.5),
               color = "white") +
     theme_void() +
     theme(legend.position = "none",
           plot.title = element_text(hjust = 0.5,
                                     face = "bold"),
           plot.margin=unit(c(.5, .5, .5, .5),"cm"),
           plot.caption = element_text(color = "#505050"),
           strip.text = element_text(face = "bold")) +
     scale_fill_manual(values = rev(c(tfff.light.green,
                                      tfff.dark.green)))


```

## Map


```{r fig.height = 10}


dk_or_ca_map() +
     geom_point(data = core_county, aes(longitude, latitude,
                                        color = core),
                size = 5,
                alpha = 0.7) +
     scale_color_manual(values = rev(c(tfff.light.green,
                                   tfff.dark.green))) +
     labs(color = "") +
     theme(legend.position = "right")




```


# Median Income

## Histogram

```{r}

ggplot(median_income, aes(estimate)) +
     geom_histogram(bins = 20) +
     scale_x_continuous(labels = dollar_format(),
                        limits = c(0, 80000)) +
     scale_y_continuous(limits = c(0, 10),
                        breaks = pretty_breaks(n = 4)) +
     labs(x = "Median income",
          y = "Number of communities")
```

## Map

```{r fig.height = 10}
dk_or_ca_map() +
     geom_point(data = median_income, aes(longitude, latitude,
                                          size = estimate),
                alpha = 0.7,
                color = tfff.dark.green) +
     labs(size = "Median Income") +
     scale_size_continuous(labels = dollar_format())

```

# Median Home Value

## Histogram

```{r}
ggplot(median_home_value, aes(estimate)) +
     geom_histogram() +
     scale_x_continuous(labels = dollar_format(),
                        limits = c(0, 350000)) +
     scale_y_continuous(limits = c(0, 12),
                        breaks = pretty_breaks(n = 5)) +
     labs(x = "Median home value",
          y = "Number of communities")

```

## Map

```{r fig.height = 10}
dk_or_ca_map() +
     geom_point(data = median_home_value, aes(longitude, latitude,
                                              size = estimate),
                alpha = 0.7,
                color = tfff.dark.green) +
     labs(size = "Median Home Value") +
     scale_size_continuous(labels = dollar_format())

```


# Latinx Population

## Histogram

```{r}
ggplot(latinx, aes(pct)) +
     geom_histogram() +
     scale_x_continuous(limits = c(0, 1),
                        labels = percent_format(accuracy = 1)) + 
     scale_y_continuous(limits = c(0, 12),
                        breaks = pretty_breaks(n = 5)) +
     labs(x = "Percent Latinx",
          y = "Number of communities")
```

## Map

```{r fig.height = 10}
dk_or_ca_map() +
     geom_point(data = latinx, aes(longitude.x, latitude.y,
                                   size = pct),
                alpha = 0.7,
                color = tfff.dark.green) +
     labs(size = "Percent Latinx") +
     scale_size_continuous(labels = percent_format(accuracy = 1))
```

# Native American Population

## Histogram

```{r}
ggplot(native_americans, aes(pct)) +
     geom_histogram() +
     scale_x_continuous(limits = c(0, 1),
                        labels = percent_format(accuracy = 1)) + 
     scale_y_continuous(limits = c(0, 12),
                        breaks = pretty_breaks(n = 5)) +
     labs(x = "Percent Native American",
          y = "Number of communities")
```

## Map

```{r fig.height = 10}
dk_or_ca_map() +
     geom_point(data = native_americans, aes(longitude.x, latitude.y,
                                             size = pct),
                alpha = 0.7,
                color = tfff.dark.green) +
     labs(size = "Percent Native American") +
     scale_size_continuous(labels = percent_format(accuracy = 1))
```

# Frontier and Remote Designation

## Bar chart

0 = Not FAR

```{r}

ggplot(far, aes(far_level)) +
     geom_bar() +
     scale_y_continuous(limits = c(0, 40)) +
     labs(x = "FAR Level",
          y = "Number of communities")

```

## Map

0 = Not FAR

```{r fig.height = 10}
dk_or_ca_map() +
     geom_point(data = far, aes(lon, lat,
                                size = far_level),
                alpha = 0.7,
                color = tfff.dark.green) +
     labs(size = "FAR Level") 

```



